#!/usr/bin/env python3
"""Generate a SELF-CONTAINED Kaggle GPU training script from the az_nn sources + decks + curriculum
opponents. Single source of truth: edit the modules, rerun this, re-upload the generated file.

The generated kaggle_train_grimm.py, when run in a Kaggle notebook (GPU on, competition attached):
  - locates cg-lib from /kaggle/input
  - writes the bundled modules + curriculum rule-agents to /kaggle/working (base64 -> no quoting issues)
  - runs self-play training and saves model_final.pth + model_arch.json to /kaggle/working for download
"""
import base64
import os

ROOT = "/Users/nickzwart/Desktop/PTCG-AI-Challenge"
AZ = os.path.join(ROOT, "analysis/az_nn")
OUT = os.path.join(AZ, "kaggle_train_grimm.py")


def b64(path):
    return base64.b64encode(open(path, "rb").read()).decode()


MODULES = {
    "nn_common.py": os.path.join(AZ, "nn_common.py"),
    "mcts_agent.py": os.path.join(AZ, "mcts_agent.py"),
    "train_core.py": os.path.join(AZ, "train_core.py"),
}
OPPS = {
    "mlucario": os.path.join(ROOT, "my-agent/gauntlet/mlucario"),
    "crustle": os.path.join(ROOT, "my-agent/gauntlet/crustle"),
    "alakazam": os.path.join(ROOT, "my-agent/alakazam_v20"),      # A: dominant mid-upper deck
    "archaludon": os.path.join(ROOT, "my-agent/gauntlet/archaludon"),  # A: 800s wall
    "starmie": os.path.join(ROOT, "my-agent/gauntlet/starmie"),   # A: fast aggro (grimm_nn0 went 0% here)
    "dragapult": os.path.join(ROOT, "my-agent/pool/dragapult_v1"),  # A: held-out
}
GRIMM_DECK = os.path.join(ROOT, "my-agent/grimmsnarl_v17/deck.csv")


def main():
    mod_b64 = {name: b64(path) for name, path in MODULES.items()}
    opp_b64 = {name: {"main.py": b64(os.path.join(d, "main.py")),
                      "deck.csv": b64(os.path.join(d, "deck.csv"))}
               for name, d in OPPS.items()}
    grimm_b64 = b64(GRIMM_DECK)

    script = '''#!/usr/bin/env python3
# ============================================================================================
# GENERATED by analysis/az_nn/build_kaggle.py  -- DO NOT EDIT HERE (edit the az_nn sources).
# Self-play training for a Transformer+MCTS Grimmsnarl, curriculum = M-Lucario + Crustle first.
# HOW TO RUN ON KAGGLE:
#   1. New Notebook in the "pokemon-tcg-ai-battle" competition; Settings -> Accelerator = GPU;
#      Internet on; add the competition data (so cg-lib + card data are under /kaggle/input).
#   2. Paste this whole file into one cell and Run All  (or upload as a script).
#   3. When done, download /kaggle/working/model_final.pth + model_arch.json.
#      Drop them into my-agent/grimm_nn0/ (replacing model.pth), then validate with round_robin.
# Scale knobs are in CFG at the bottom. Bigger model/more iters/more search = stronger but slower.
# ============================================================================================
import base64, glob, os, sys

# --- locate the cg engine robustly (cg-lib dir, OR the cg package by its api.py, OR already importable) ---
def _find_cg_root():
    try:
        import cg as _c
        return os.path.dirname(os.path.dirname(os.path.abspath(_c.__file__)))
    except Exception:
        pass
    for _pat in ("/kaggle/input/**/cg-lib", "/kaggle/input/**/cg/api.py"):
        for _hit in glob.glob(_pat, recursive=True):
            if _hit.endswith("cg-lib") and os.path.isdir(_hit):
                return _hit                       # add cg-lib dir (contains the cg package)
            if _hit.endswith(os.path.join("cg", "api.py")):
                return os.path.dirname(os.path.dirname(_hit))   # add parent of the cg package
    return None

_CGROOT = _find_cg_root()
if _CGROOT and _CGROOT not in sys.path:
    sys.path.append(_CGROOT)
try:
    import cg  # noqa: F401
    print("cg engine found at:", _CGROOT or "(already importable)", flush=True)
except Exception:
    print("ERROR: cg engine not found. Attach the 'pokemon-tcg-ai-battle' competition as an Input "
          "(Add Input -> Competitions), then re-run. Run the diagnostic cell to see the layout.", flush=True)
    raise

WORK = "/kaggle/working" if os.path.isdir("/kaggle/working") else "."
os.makedirs(WORK, exist_ok=True)

MODULES = %(mod)r
OPPS = %(opp)r
GRIMM_DECK_B64 = %(grimm)r

# --- materialize bundled modules ---
for _name, _b in MODULES.items():
    open(os.path.join(WORK, _name), "wb").write(base64.b64decode(_b))
# --- materialize curriculum opponents ---
_OPP_ROOT = os.path.join(WORK, "opp")
for _name, _files in OPPS.items():
    _d = os.path.join(_OPP_ROOT, _name)
    os.makedirs(_d, exist_ok=True)
    for _fn, _b in _files.items():
        open(os.path.join(_d, _fn), "wb").write(base64.b64decode(_b))
# --- materialize our Grimmsnarl deck dir ---
_GDIR = os.path.join(WORK, "grimm")
os.makedirs(_GDIR, exist_ok=True)
open(os.path.join(_GDIR, "deck.csv"), "wb").write(base64.b64decode(GRIMM_DECK_B64))

sys.path.insert(0, WORK)
from train_core import run_training

# #1 WARM-START: locate the expert-replay dataset attached under /kaggle/input (grimm_warmstart.pkl)
_ws = glob.glob("/kaggle/input/**/grimm_warmstart.pkl", recursive=True)
_WS_PATH = _ws[0] if _ws else None
print("warm-start data:", _WS_PATH or "(NONE attached -> self-play from scratch = weak)", flush=True)

CFG = {
    "deck_dir": _GDIR,
    # A (iteration 2): FULL curriculum — the decks grimm_nn0 v1 failed against (validation: it lost
    # badly to Starmie, Alakazam, Archaludon). Mirror stays the plurality; field decks weighted in.
    "curriculum": [
        {"dir": os.path.join(_OPP_ROOT, "alakazam"), "weight": 2},    # dominant mid-upper deck
        {"dir": os.path.join(_OPP_ROOT, "archaludon"), "weight": 2},  # 800s wall
        {"dir": os.path.join(_OPP_ROOT, "mlucario"), "weight": 2},    # floor deck
        {"dir": os.path.join(_OPP_ROOT, "starmie"), "weight": 1},     # fast aggro (v1 lost here)
        {"dir": os.path.join(_OPP_ROOT, "crustle"), "weight": 1},
        {"dir": os.path.join(_OPP_ROOT, "dragapult"), "weight": 1},
    ],
    "mirror_weight": 6,          # mirror self-play stays the plurality (mirror dominates the top band)
    "iterations": 30,            # far more than v1's 12 (v1 was undertrained = "beats random" tier)
    "games_per_iter": 250,
    "eval_games": 40,
    "search_count": 48,          # #2 DEEPER MCTS (was 14 = too shallow for strong targets)
    "warmstart": _WS_PATH,       # #1 expert warm-start (BC policy + value grounding before self-play)
    "pretrain_epochs": 4,
    "model": (128, 4, 512, 2, 2),  # DEEPER body (4 heads, 512 ff, 2+2 layers) but d_model=128 kept so
    # the embedding tables (decoder_bag 73847 x d_model) stay ~48MB = deployable (256 -> ~100MB, risks
    # the Kaggle submission size limit). v1's real gaps were curriculum + iters, not mainly capacity.
    # NOTE: full curriculum + 30 iters => a longer run (~2-3 hr). The deployed grimm_nn0 agent reads
    # model_arch.json, so these dims load automatically — no agent-side code change needed.
    "lr": 3e-4,
    "batch_size": 128,
    "lambda_td": 0.9,
    "t14_adjudicate": True,
    "stop_turn": 14,
    "out_dir": WORK,
    "device": None,              # auto -> cuda
}

import torch
print("CUDA available:", torch.cuda.is_available(),
      "| device:", (torch.cuda.get_device_name(0) if torch.cuda.is_available() else "cpu"), flush=True)
run_training(CFG)
print("DONE. Download:", os.path.join(WORK, "model_final.pth"), "and model_arch.json")
''' % {"mod": mod_b64, "opp": opp_b64, "grimm": grimm_b64}

    open(OUT, "w").write(script)
    kb = os.path.getsize(OUT) / 1024
    print(f"wrote {OUT}  ({kb:.0f} KB)")


if __name__ == "__main__":
    main()
